project3/urls.py
from django.urls import path
from . import views
from .views import PostDetailView

app_name = 'project3'

urlpatterns = [
    path('post_list/', views.post_list, name='post_list'),
    path('post_detail/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
]

test2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('project3.urls', namespace='project3') ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


project3/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    counted_views = models.IntegerField(default=0)

    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title


# Create your models here.

project3/views.py
from datetime import datetime
from django.views.generic import DetailView
from django.shortcuts import render, get_object_or_404
from .models import *

def post_list(request):
    posts = Post.objects.all().order_by('-published_date')
    return render(request, 'list_post.html', {'posts': posts})

#def post_detail(request, pk):
 #   post = get_object_or_404(Post, pk=pk)
  #  post.counted_views = post.counted_views + 1
   # post.save()
    #return render(request, 'post_detail.html', {'post': post})


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        post.counted_views += 1
        post.save()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object

        previous_post = Post.objects.filter(published_date__lt=post.published_date).order_by('-published_date').first()
        next_post = Post.objects.filter(published_date__gt=post.published_date).order_by('published_date').first()

        context['previous_post'] = previous_post
        context['next_post'] = next_post
        return context

# Create your views here.

project3/templates/list_post.html
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for post in posts %}
    <div class="post-item">
         <h2><a href="{% url 'project3:post_detail' post.pk %}">{{ post.title }}</a></h2>
        <p>{{ post.content|excerpt_words:20 }}</p>

        {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }}" style="width: 100px; height: 100px;">
        {% endif %}
        <p>تاریخ انتشار: {{ post.published_date }}</p>
    </div>
{% endfor %}

</body>
</html>

project3/templates/post_detail.html

<body>
<h1>{{ post.title }}</h1>
<p>p{{ post.content }}</p>
<p>Published: {{ post.publish }}</p>
<p>Views: {{ post.counted_views }}</p>

{% if post.image %}
        <img src="{{ post.image.url }}" alt="{{ post.title }}" style="width: 100px; height: 100px;">
{% else %}
        <p>No image available for this post.</p>
{% endif %}
<a href="{% url 'project3:post_detail' post.pk %}">Back to Posts</a>

<div class="post-navigation">
    {% if previous_post %}
        <div class="previous-post">
            <a href="{% url 'project3:post_detail' previous_post.pk %}">
                <P>Pervious_post:</P>
                <img src="{{ previous_post.image.url }}" alt="{{ previous_post.title }}" style="width: 50px; height: 50px;">
                <span>{{ previous_post.title }}</span>
            </a>
        </div>
    {% endif %}

    {% if next_post %}
        <div class="next-post">
            <a href="{% url 'project3:post_detail' next_post.pk %}">
                {% if next_post.image %}
                    <p>Next_post:</p>
                <img src="{{ next_post.image.url }}" alt="{{ next_post.title }}" style="width: 50px; height: 50px;">
                    {% else %}
                    <p>No image available</p>
                    {% endif %}
                    <span>{{ next_post.title }}</span>
            </a>
        </div>
    {% endif %}
</div>

</body>
